### ISSUE TITLE
Feature Request: Support adding multiple codeboxes

### ISSUE THREAD

**Issue by dvn0** [GreenMeteor/humhub-codebox-module#7]
Convenient module, but I want to be able to add multiple different codeboxes, so I can display multiple things.

**Comment by ArchBlood** [comment]
It may take some time before I can implement such a function, but I do like the idea.

**Comment by dvn0** [comment]
If it wouldn't be too much overhead to provide a little guidance then I may be able to find time to work on this myself in a PR.

**Comment by ArchBlood** [comment]
> If it wouldn't be too much overhead to provide a little guidance then I may be able to find time to work on this myself in a PR.

Thank you for the offer, currently to do something like this we'd need to update everything so that it's an ActiveRecord instead of a normal Model;

Adding to that we'd need the following;
- Reworking of [CodeboxFrame widget](https://github.com/GreenMeteor/codebox/blob/master/widgets/CodeboxFrame.php)
- Reworking of [ConfigureForm](https://github.com/GreenMeteor/codebox/blob/master/models/ConfigureForm.php)
- Reworking of [codeboxframe view](https://github.com/GreenMeteor/codebox/blob/master/widgets/views/codeboxframe.php)

**Comment by ArchBlood** [comment]
Okay, so here's the current state of this request, I've been trying to work on the implementation requested and here's what I've gotten done so far;

![Screenshot_1](https://github.com/GreenMeteor/codebox/assets/35392110/4b5d2ee5-9244-415f-bd2b-5df7087684a0)
![Screenshot_2](https://github.com/GreenMeteor/codebox/assets/35392110/a28fa944-534c-45e4-851a-95f8c12ca1c1)


Note: Such changes requires much refactoring, and I'm not exactly sure if it's currently worth time implementing as a free service, I say this because this would also require more maintaining of code compared to the original intent of the module.

**Comment by dvn0** [comment]
Looks great, that's pretty much exactly what I imagined. I like how you have the box titles.

>  I'm not exactly sure if it's currently worth time implementing as a free service, I say this because this would also require more maintaining of code compared to the original intent of the module.

You mean you should get paid for your work on this, or that the module shouldn't be free if it gets this feature?

**Comment by ArchBlood** [comment]
> You mean you should get paid for your work on this, or that the module shouldn't be free if it gets this feature?

I try my best to keep as many modules free as possible, but maintaining the code is very time consuming, and I currently have little time at this moment due to other requests, I'll confirm that in v1.2.0 this will be implemented though.

**Comment by dvn0** [comment]
Yea, understood. Sorry I couldn't be more helpful this time. Thanks much for your work.

**Comment by ArchBlood** [comment]
> Yea, understood. Sorry I couldn't be more helpful this time. Thanks much for your work.

You can install the latest version from [latest](https://github.com/GreenMeteor/codebox/releases/latest) releases, or wait till HumHub v1.16.0 stable is released.

**Comment by dvn0** [comment]
Thanks. I'll try it out on my test deployment now, and then wait for the HumHub release for production.
